CREATE OR REPLACE FUNCTION &pmaUsername..HEXTOINTEGER (h VARCHAR2) RETURN NUMBER IS
BEGIN
   IF NVL (LENGTH (h), 1) = 1
   THEN
      RETURN INSTR ('0123456789ABCDEF', h) - 1;
   ELSE
      RETURN 16 * HEXTOINTEGER (SUBSTR (h, 1, LENGTH (h) - 1)) + INSTR ('0123456789ABCDEF', SUBSTR (h, -1)) - 1;
   END IF;
END;