Ext.define('Apm.model.Transaction',
{
	extend	: 'Ext.data.Model',
	id		: 'idTransactionModel',
	fields: 
			[				
				{name: 'id',						        mapping: 'transactionId'	, type: 'int'	, useNull: true},
				{name: 'status',					        mapping: 'status'},
				{name: 'systemDateTime',                    mapping: 'systemDateTime'},
				{name: 'requestDateTime',                   mapping: 'requestDateTime'},
				{name: 'responseDateTime',                  mapping: 'responseDateTime'},
				{name: 'responseCode',                      mapping: 'responseCode'},
				{name: 'errorDescription',                  mapping: 'errorDescription'},
				{name: 'transactionType',		            mapping: 'transactionType'},
				{name: 'requestPanId',				        mapping: 'requestPanId'	, type: 'int'	, useNull: true},
				{name: 'requestTokenAppSeqNum',		        mapping: 'requestTokenAppSeqNum'	, type: 'int'	, useNull: true},
				{name: 'responseTokenAppSeqNum',	        mapping: 'responseTokenAppSeqNum'	, type: 'int'	, useNull: true},
				{name: 'responsePanId',				        mapping: 'responsePanId'	, type: 'int'	, useNull: true},
				{name: 'responseIssuerTokenProductCode',    mapping: 'responseIssuerTokenProductCode'},
				{name: 'requestIssuerTokenProductCode',     mapping: 'requestIssuerTokenProductCode'},
				{name: 'requestPinExpiryDate',              mapping: 'requestPinExpiryDate'},
				{name: 'requestPanExpiryDate',              mapping: 'requestPanExpiryDate'},
				{name: 'requestPinDeliveryMethod',			mapping: 'requestPinDeliveryMethod'	, type: 'int'	, useNull: true},
			/*	{name: 'requestFirstName',                  mapping: 'requestFirstName'},
				{name: 'requestMiddleName',                 mapping: 'requestMiddleName'},
				{name: 'requestLastName',                   mapping: 'requestLastName'},
				{name: 'requestAddress1',                   mapping: 'requestAddress1'},
				{name: 'requestAddress2',                   mapping: 'requestAddress2'},
				{name: 'requestAddress3',                   mapping: 'requestAddress3'},
				{name: 'requestAddress4',                   mapping: 'requestAddress4'},
				{name: 'requestAddress5',                   mapping: 'requestAddress5'},
				{name: 'requestAddress6',                   mapping: 'requestAddress6'},
				{name: 'requestTown',                       mapping: 'requestTown'},
				{name: 'requestPostCode',                   mapping: 'requestPostCode'},  */
				{name: 'requestCountryCode',                mapping: 'requestCountryCode'},
				{name: 'requestCompanyName',                mapping: 'requestCompanyName'},
				{name: 'requestCompanyContact',             mapping: 'requestCompanyContact'},
				{name: 'requestNumberOfTokens',			    mapping: 'requestNumberOfTokens'	, type: 'int'	, useNull: true},
				{name: 'requestGeneratePinFlag',            mapping: 'requestGeneratePinFlag'},
				{name: 'requestGeneratePukFlag',            mapping: 'requestGeneratePukFlag'},
				{name: 'requestPanDisplay',                 mapping: 'requestPanDisplay'},
				{name: 'responsePanDisplay',                mapping: 'responsePanDisplay'},
			]
	
});	
